### ISSUE TITLE
Import Pyspark-cassandra in spark workers failing.

### ISSUE THREAD

**Issue by komal436** [anguenot/pyspark-cassandra#16]
Hi,
I am using a pyspark + Cassandra to work on an issue.
Setup Details:
1. the spark is downloaded and kept in my D:\spark\spark
2. The scala in D:\spark\scala
3. Hadoop in D:\spark\hadoop
4. Got the Cassandra and ran the Cassandra.bat file and it works fine.
5. All the spark, scala and Hadoop paths are set in the environment variables and the updated the path variable with Cassandra bin and spark bin
6. I downloaded pyspark_Cassandra spark packages and kept in D:\spark\spark\jars folder.
Running the import pyspark_cassandra in the python env is throwing import_module error.
How to make pyspark_cassandra available to the python environment globally.

Error:

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-15-7faea3dea615> in <module>()
----> 1 rdd.take(2)

D:\spark\spark\python\pyspark\rdd.py in take(self, num)
   1341 
   1342             p = range(partsScanned, min(partsScanned + numPartsToTry, totalParts))
-> 1343             res = self.context.runJob(self, takeUpToNumLeft, p)
   1344 
   1345             items += res

D:\spark\spark\python\pyspark\context.py in runJob(self, rdd, partitionFunc, partitions, allowLocal)
    990         # SparkContext#runJob.
    991         mappedRDD = rdd.mapPartitions(partitionFunc)
--> 992         port = self._jvm.PythonRDD.runJob(self._jsc.sc(), mappedRDD._jrdd, partitions)
    993         return list(_load_from_socket(port, mappedRDD._jrdd_deserializer))
    994 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\py4j\java_gateway.py in __call__(self, *args)
   1158         answer = self.gateway_client.send_command(command)
   1159         return_value = get_return_value(
-> 1160             answer, self.gateway_client, self.target_id, self.name)
   1161 
   1162         for temp_arg in temp_args:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    318                 raise Py4JJavaError(
    319                     "An error occurred while calling {0}{1}{2}.\n".
--> 320                     format(target_id, ".", name), value)
    321             else:
    322                 raise Py4JError(

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 9 in stage 4.0 failed 1 times, most recent failure: Lost task 9.0 in stage 4.0 (TID 55, localhost, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 138, in dump_stream
    for obj in iterator:
  File "D:\spark\spark\python\pyspark\rdd.py", line 1752, in add_shuffle_key
    for k, v in iterator:
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 144, in load_stream
    yield self._read_with_length(stream)
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 451, in loads
    return pickle.loads(obj, encoding=encoding)
ModuleNotFoundError: No module named 'pyspark_cassandra'

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.api.python.PairwiseRDD.compute(PythonRDD.scala:395)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at org.apache.spark.api.python.PythonRDD$.runJob(PythonRDD.scala:446)
	at org.apache.spark.api.python.PythonRDD.runJob(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\worker.py", line 177, in main
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\worker.py", line 172, in process
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 138, in dump_stream
    for obj in iterator:
  File "D:\spark\spark\python\pyspark\rdd.py", line 1752, in add_shuffle_key
    for k, v in iterator:
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 144, in load_stream
    yield self._read_with_length(stream)
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "D:\spark\spark\python\lib\pyspark.zip\pyspark\serializers.py", line 451, in loads
    return pickle.loads(obj, encoding=encoding)
ModuleNotFoundError: No module named 'pyspark_cassandra'

	at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
	at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
	at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.api.python.PairwiseRDD.compute(PythonRDD.scala:395)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more

**Comment by komal436** [comment]
I got it fixed by copying the pyspark-cassandra to the python packages. But if the pyspark-cassandra can be part of pip packages, it will easy.

**Comment by anguenot** [comment]
@komal436  glad you managed to fix your issue. I am planning on working on a pip installed package for `pyspark-cassandra`. Will keep you posted.

**Comment by Chesterguan** [comment]
> I got it fixed by copying the pyspark-cassandra to the python packages. But if the pyspark-cassandra can be part of pip packages, it will easy.

Hi, Could you please provide the methods to copy the pyspark-cassandra into the python packages ?  Thanks so much !
