### ISSUE TITLE
Facing issue running as flat jar [py4j.protocol.Py4JJavaError: An error occurred while calling o38.loadClass. : java.lang.ClassNotFoundException: pyspark_cassandra.PythonHelper]

### ISSUE THREAD

**Issue by akm523** [anguenot/pyspark-cassandra#25]
I am facing this issue while running a pyspark (cassandra flat jar version 0.7.0) program for spark-2.0.1 (scala 2.11) and python 2.7.
Following issue is occuring while trying to save cassandra (table as mentioned in the example):
Also tried  this command : bin/spark-submit --jars ~/software/spark-cassandra-connector_2.10-2.0.1.jar --driver-class-path ~/software/spark-cassandra-connector_2.10-2.0.1.jar --py-files ~/software/pyspark-cassandra-0.7.0.jar --conf spark.cassandra.connection.host=127 --master spark://127.0.0.1:7077 ~/pipeline/CassandraModel.py

File "/home/phenodoop/pipeline/CassandraModel.py", line 20, in <module>
    rdd.saveToCassandra("moviedb", "movies", ('id','title','year'))
  File "/home/phenodoop/software/pyspark-cassandra-0.7.0.jar/pyspark_cassandra/rdd.py", line 85, in saveToCassandra
  File "/home/phenodoop/software/pyspark-cassandra-0.7.0.jar/pyspark_cassandra/util.py", line 99, in helper
  File "/home/phenodoop/software/pyspark-cassandra-0.7.0.jar/pyspark_cassandra/util.py", line 88, in load_class
  File "/home/phenodoop/spark-2.0.1/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/home/phenodoop/spark-2.0.1/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o38.loadClass.
: java.lang.ClassNotFoundException: pyspark_cassandra.PythonHelper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)

**Comment by akm523** [comment]
Building from the source code solves the issue!! Sorry for this post

**Comment by GeneralZYQ** [comment]
> Building from the source code solves the issue!! Sorry for this post

What's your meaning of building from the source code? 
Because I met the same question.

**Comment by Shubham-Gupte** [comment]
Can this issue be repoened? I am dealing with the same error

**Comment by akm523** [comment]
If the issue persists build pyspark-cassandra-0.7.0.jar and spark-cassandra-connector_2.10-2.0.1.jar from the source code, do not use the prebuilt package

**Comment by anguenot** [comment]
@akm523  @Shubham-Gupte  @GeneralZYQ please see README file:

> The current version of PySpark Cassandra is successfully used with Spark version 2.3.x.
> 
> For Spark versions 2.0.x, 2.1.x, 2.2.x: use version 0.9.0
