### ISSUE TITLE
Unable to read empty collections

### ISSUE THREAD

**Issue by ndamclean** [anguenot/pyspark-cassandra#37]
Steps to reproduce issue:
1. create table with frozen collection column
    ```
    CREATE TABLE test_frozen_collection (
        key int,
        collection frozen<list<text>>,
        PRIMARY KEY (key)
    );
    ```
1. insert row with empty collection
    ```
    INSERT INTO test_frozen_collection (key, collection) VALUES (1, []);
    ```
1. attempt to read row in pyspark
    ```
    import pyspark_cassandra
    pyspark_cassandra.monkey_patch_sc(sc)
    rdd = sc.cassandraTable('test_keyspace', 'test_frozen_collection')
    rdd.where('key=?', 1).collect()
    ```
1.
    error:
    `net.razorvine.pickle.PickleException: couldn't introspect javabean: java.lang.IllegalArgumentException: wrong number of arguments`

Note, if the collection column contains a `null` value, `pyspark` is happy
```
INSERT INTO test_frozen_collection (key, collection) VALUES (1, null);
```

**Comment by ndamclean** [comment]
full stack trace:
```
18/06/28 23:16:43 ERROR executor.Executor: Exception in task 0.0 in stage 1.0 (TID 1)
net.razorvine.pickle.PickleException: couldn't introspect javabean: java.lang.IllegalArgumentException: wrong number of arguments
	at net.razorvine.pickle.Pickler.put_javabean(Pickler.java:705)
	at net.razorvine.pickle.Pickler.dispatch(Pickler.java:323)
	at net.razorvine.pickle.Pickler.save(Pickler.java:137)
	at net.razorvine.pickle.Pickler.put_collection(Pickler.java:335)
	at net.razorvine.pickle.Pickler.dispatch(Pickler.java:314)
	at net.razorvine.pickle.Pickler.save(Pickler.java:137)
	at pyspark_util.ListPickler$.pickle(Pickling.scala:252)
	at net.razorvine.pickle.Pickler.dispatch(Pickler.java:248)
	at net.razorvine.pickle.Pickler.save(Pickler.java:137)
	at pyspark_util.StructPickler$class.pickle(Pickling.scala:151)
	at pyspark_cassandra.PlainRowPickler$.pickle(Pickling.scala:47)
	at net.razorvine.pickle.Pickler.dispatch(Pickler.java:248)
	at net.razorvine.pickle.Pickler.save(Pickler.java:137)
	at net.razorvine.pickle.Pickler.put_arrayOfObjects(Pickler.java:493)
	at net.razorvine.pickle.Pickler.dispatch(Pickler.java:205)
	at net.razorvine.pickle.Pickler.save(Pickler.java:137)
	at net.razorvine.pickle.Pickler.dump(Pickler.java:107)
	at net.razorvine.pickle.Pickler.dumps(Pickler.java:92)
	at pyspark_util.BatchPickler$$anonfun$apply$1.apply(Pickling.scala:133)
	at pyspark_util.BatchPickler$$anonfun$apply$1.apply(Pickling.scala:133)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1$$anonfun$13.apply(RDD.scala:936)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
