### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.datastax.spark.connector.writer.RowWriterFactory

### ISSUE THREAD

**Issue by cyn501** [anguenot/pyspark-cassandra#42]
My code is :

```’import pyspark_cassandra
from pyspark_cassandra import CassandraSparkContext
from pyspark import SparkConf
from pyspark.sql import SQLContext
from pyspark import SparkContext


conf = SparkConf() \
	.setAppName("PySpark Cassandra Test") \
	.setMaster("spark://192.192.141.21:7077") \
	.set("spark.cassandra.connection.host", "192.192.141.26:9042")

sc = CassandraSparkContext(conf=conf)
# sc = SparkContext(conf=conf)
# sqlContext = SQLContext(sc)
#sc = SQLContext(conf=conf)
dd = sc.cassandraTable("oltpdb", "XiangWan")\
	.select("dt", "wid") \
	.where("wid='XiangWan001'") \
	.collect()
```

And the command line is
`spark-submit --jars /root/model/pyspark-cassandra-0.10.1.jar /root/model/connect_cannandra_via_spark.py`

And I got the error:
```
19/04/12 14:14:56 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/12 14:14:56 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/04/12 14:14:56 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
19/04/12 14:14:56 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
Traceback (most recent call last):
  File "/root/model/connect_cannandra_via_spark.py", line 17, in <module>
    dd = sc.cassandraTable("oltpdb", "XiangWan")\
  File "/root/anaconda3/lib/python3.6/site-packages/pyspark_cassandra-0.9.0-py3.6.egg/pyspark_cassandra/context.py", line 33, in cassandraTable
  File "/root/anaconda3/lib/python3.6/site-packages/pyspark_cassandra-0.9.0-py3.6.egg/pyspark_cassandra/rdd.py", line 324, in __init__
  File "/root/anaconda3/lib/python3.6/site-packages/pyspark_cassandra-0.9.0-py3.6.egg/pyspark_cassandra/rdd.py", line 213, in _helper
  File "/root/anaconda3/lib/python3.6/site-packages/pyspark_cassandra-0.9.0-py3.6.egg/pyspark_cassandra/util.py", line 99, in helper
  File "/root/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/root/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o26.newInstance.
: java.lang.NoClassDefFoundError: com/datastax/spark/connector/writer/RowWriterFactory
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.datastax.spark.connector.writer.RowWriterFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
```

So what should I do?

**Comment by cyn501** [comment]
@anguenot

**Comment by anguenot** [comment]
The log indicated you are using `/root/anaconda3/lib/python3.6/site-packages/pyspark_cassandra-0.9.0-py3.6.egg` which is not the same version as the one you are specifying in the spark-summit command.

**Comment by cyn501** [comment]
> The log indicated you are using `/root/anaconda3/lib/python3.6/site-packages/pyspark_cassandra-0.9.0-py3.6.egg` which is not the same version as the one you are specifying in the spark-summit command.

I  put the jars and the code files into the same folder.
![Image 1](https://user-images.githubusercontent.com/28639076/56256962-53c62e00-60fd-11e9-963b-e4e9909a3fe5.png)

Then the command line is
```
spark-submit --jars pyspark-cassandra-0.10.1.jar connect_cannandra_via_spark.py
```

So I got:
```
19/04/17 10:42:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/17 10:42:51 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
Traceback (most recent call last):
  File "/root/model/pyspark_cassandra_test/connect_cannandra_via_spark.py", line 17, in <module>
    dd = sc.cassandraTable("oltpdb", "xiangwan")\
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/context.py", line 33, in cassandraTable
    return CassandraTableScanRDD(self, *args, **kwargs)
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/rdd.py", line 324, in __init__
    self.crdd = self._helper \
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/rdd.py", line 213, in _helper
    return helper(self.ctx)
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/util.py", line 99, in helper
    "pyspark_cassandra.PythonHelper").newInstance()
  File "/root/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/root/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o26.newInstance.
: java.lang.NoClassDefFoundError: com/datastax/spark/connector/writer/RowWriterFactory
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.datastax.spark.connector.writer.RowWriterFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
```

Then I tried to use another jar file.The command line is:
```
[root@CDH21 pyspark_cassandra_test]# spark-submit --jars spark-cassandra-connector-2.4.0-s_2.11.jar connect_cannandra_via_spark.py
```
The result is:

```
19/04/17 10:45:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/17 10:45:40 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
Traceback (most recent call last):
  File "/root/model/pyspark_cassandra_test/connect_cannandra_via_spark.py", line 17, in <module>
    dd = sc.cassandraTable("oltpdb", "xiangwan")\
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/context.py", line 33, in cassandraTable
    return CassandraTableScanRDD(self, *args, **kwargs)
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/rdd.py", line 324, in __init__
    self.crdd = self._helper \
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/rdd.py", line 213, in _helper
    return helper(self.ctx)
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/util.py", line 99, in helper
    "pyspark_cassandra.PythonHelper").newInstance()
  File "/root/model/pyspark_cassandra_test/pyspark_cassandra/util.py", line 88, in load_class
    .loadClass(name)
  File "/root/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/root/spark-2.2.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o25.loadClass.
: java.lang.ClassNotFoundException: pyspark_cassandra.PythonHelper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
```

So what can I do?

**Comment by jiangzz** [comment]
我也遇到了和你同样的问题，使用spark-submit --jars 第三方依赖jars --class 入口类  资源jar 运行的时候，系统日志显示第三方依赖jar已经add上去了，但是在运行DriverWrap的时候，就抛出class not found 异常

**Comment by anguenot** [comment]
@cyn501  Version 0.10.1 dropped Spark 2.2.0 support. Latest version working with Spark 2.2.0 is 0.9.0

**Comment by cyn501** [comment]
> 我也遇到了和你同样的问题，使用spark-submit --jars 第三方依赖jars --class 入口类 资源jar 运行的时候，系统日志显示第三方依赖jar已经add上去了，但是在运行DriverWrap的时候，就抛出class not found 异常

你的问题解决没？

**Comment by cyn501** [comment]
@jiangzz
