### ISSUE TITLE
spark-submit gives TypeError

### ISSUE THREAD

**Issue by sarathsairam** [anguenot/pyspark-cassandra#53]
bash-4.4# ./spark-submit --jars ./pyspark-cassandra-2.4.0.jar --py-files ./pyspark-cassandra-2.4.0.jar --conf spark.cassandra.connection.host=192.168.158.133 --conf spark.port.maxRetries=50 t.py

2020-01-20 09:54:07 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "/spark/bin/t.py", line 3, in <module>
    import pyspark_cassandra
  File "/spark/bin/pyspark-cassandra-2.4.0.jar/pyspark_cassandra/__init__.py", line 54, in <module>
  File "/spark/bin/pyspark-cassandra-2.4.0.jar/pyspark_cassandra/context.py", line 21, in monkey_patch_sc
TypeError: __class__ assignment: only for heap types
2020-01-20 09:54:08 INFO  ShutdownHookManager:54 - Shutdown hook called
2020-01-20 09:54:08 INFO  ShutdownHookManager:54 - Deleting directory /tmp/spark-246b1a89-fb6d-40eb-9de9-2b43b625bf49

pyspark shell is working but while submitting a job, it is throwing the above error

**initial lines of t.py script**

```
from pyspark import SparkContext as sc
from pyspark.sql import SQLContext

**import pyspark_cassandra**

sqlctx = SQLContext(sc)

```

**Comment by sarathsairam** [comment]
This is when the maximum open input files limit is not sufficient.. So, change this setting at os level & this will work..

**Comment by sarathsairam** [comment]
There is some issue with this & hence we have built the spark-cassandra-connector from source using scala build tool (sbt) which solved the issue
