### ISSUE TITLE
Error while calling cassandraTable

### ISSUE THREAD

**Issue by kalikho** [anguenot/pyspark-cassandra#59]
![error-2](https://user-images.githubusercontent.com/42250206/152493683-dfdb2f83-1403-49cf-95eb-d1304d1aee15.png)

**Comment by kalikho** [comment]
An error occurred while calling o61.cassandraTable.
: java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
	at com.datastax.spark.connector.util.ConfigParameter.<init>(ConfigParameter.scala:7)
	at com.datastax.spark.connector.rdd.ReadConf$.<init>(ReadConf.scala:38)
	at com.datastax.spark.connector.rdd.ReadConf$.<clinit>(ReadConf.scala)
	at pyspark_cassandra.Utils$.parseReadConf(Utils.scala:59)
	at pyspark_cassandra.PythonHelper.cassandraTable(PythonHelper.scala:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

An error occurred while calling o61.cassandraTable.
: java.lang.NoClassDefFoundError: Could not initialize class com.datastax.spark.connector.rdd.ReadConf$
	at pyspark_cassandra.Utils$.parseReadConf(Utils.scala:59)
	at pyspark_cassandra.PythonHelper.cassandraTable(PythonHelper.scala:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

An error occurred while calling o61.cassandraTable.
: java.lang.NoClassDefFoundError: Could not initialize class com.datastax.spark.connector.rdd.ReadConf$
	at pyspark_cassandra.Utils$.parseReadConf(Utils.scala:59)
	at pyspark_cassandra.PythonHelper.cassandraTable(PythonHelper.scala:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

22/02/04 13:35:54 INFO SparkContext: Invoking stop() from shutdown hook
22/02/04 13:35:54 INFO StandaloneSchedulerBackend: Shutting down all executors
22/02/04 13:35:54 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
22/02/04 13:35:54 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
22/02/04 13:35:54 INFO MemoryStore: MemoryStore cleared
22/02/04 13:35:54 INFO BlockManager: BlockManager stopped
22/02/04 13:35:54 INFO BlockManagerMaster: BlockManagerMaster stopped
22/02/04 13:35:54 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
22/02/04 13:35:54 INFO SparkContext: Successfully stopped SparkContext
22/02/04 13:35:54 INFO ShutdownHookManager: Shutdown hook called
22/02/04 13:35:54 

Scala Version : 2.11.12
Pyspark Cassandra : 2.4.0
